eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
         hostname: localhost
spring:
   application:
      name: USERSERVICE
server:
   port: 9001
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
     exposure:
       include: health
  endpoint:
    health:
     show-details: always

resilience4j.circuitbreaker:
    configs:
        department:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10